[project]
name = "youtube-trend-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=0.105.0",
    "crewai-tools>=0.37.0",
    "ollama>=0.4.7",
    "streamlit>=1.43.1",
]
